export type CssSupportStatus = 'full' | 'partial' | 'todo'

export type CssSupportEffect = 'layout' | 'hit-testing' | 'visual' | 'inert' | 'source'

export type CssSupportOwnerArea = 'css-parser' | 'taffy-adapter' | 'hit-testing' | 'text' | 'dom-api'

export type CssSupportParityStatus = 'covered' | 'partial' | 'missing' | 'not-applicable'

export type CssSupportNoteKind =
  | 'browser-parity'
  | 'behavior-quirk'
  | 'implementation-quirk'
  | 'taffy-compat'
  | 'limitation'
  | 'todo'

export type CssSupportNote = {
  kind: CssSupportNoteKind
  text: string
}

export type CssSupportEntry = {
  id: string
  title: string
  status: CssSupportStatus
  effect: CssSupportEffect
  ownerArea: CssSupportOwnerArea
  parityStatus: CssSupportParityStatus
  properties: readonly string[]
  elements?: readonly string[]
  values?: readonly string[]
  parity?: readonly string[]
  notes: readonly CssSupportNote[]
}

export const cssSupportInventory: readonly CssSupportEntry[] = [
  {
    id: 'stylesheet-sources-and-selectors',
    title: 'Stylesheet sources and selectors',
    status: 'partial',
    effect: 'source',
    ownerArea: 'css-parser',
    parityStatus: 'partial',
    properties: [],
    parity: ['selector-matching', 'selector-source-order-tie', 'selector-specificity'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Configured stylesheets, style elements, selector lists, specificity, and source-order ties are covered by parity fixtures.',
      },
      {
        kind: 'limitation',
        text: 'External stylesheets, at-rules, sibling combinators, pseudo-elements, and most pseudo-classes are not implemented.',
      },
    ],
  },
  {
    id: 'display',
    title: 'Display model',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: ['display'],
    values: [
      'block',
      'inline',
      'inline-block',
      'flow-root',
      'list-item',
      'flex',
      'inline-flex',
      'grid',
      'inline-grid',
      'contents',
      'none',
    ],
    parity: ['display-aliases', 'display-contents', 'display-none', 'static-block-flow', 'flex-row', 'grid-explicit-tracks'],
    notes: [
      {
        kind: 'taffy-compat',
        text: 'Authored inline, inline-block, flow-root, and list-item are blockified; inline-flex and inline-grid are mapped to flex and grid.',
      },
      {
        kind: 'limitation',
        text: 'Inline formatting and list marker layout are not modeled.',
      },
      {
        kind: 'browser-parity',
        text: 'display: contents has parity coverage for parent box removal plus block and flex child flattening.',
      },
    ],
  },
  {
    id: 'positioning',
    title: 'Positioning and insets',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'covered',
    properties: [
      'position',
      'left',
      'right',
      'top',
      'bottom',
      'inset',
      'inset-inline',
      'inset-block',
      'inset-inline-start',
      'inset-inline-end',
      'inset-block-start',
      'inset-block-end',
      'z-index',
    ],
    values: ['static', 'relative', 'absolute', 'fixed', '<px>', 'auto', '<integer>'],
    parity: [
      'absolute-overlap',
      'absolute-positioned-containing-block',
      'fixed-inside-scrolled-ancestor',
      'fixed-inset-full-viewport',
      'inset-two-value-shorthand',
      'relative-offset-flow',
      'right-bottom-positioning',
      'z-index-dom-order',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Relative offsets, absolute containing blocks, fixed viewport positioning, fixed descendants in scrolled ancestors, opposing insets, CSS-wide static resets, and z-index ordering have parity fixtures.',
      },
      {
        kind: 'taffy-compat',
        text: 'Fixed positioning is represented through Taffy absolute positioning in the viewport-rooted layout tree.',
      },
    ],
  },
  {
    id: 'box-sizing-and-dimensions',
    title: 'Box sizing and dimensions',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'box-sizing',
      'width',
      'height',
      'inline-size',
      'block-size',
      'min-width',
      'min-height',
      'min-inline-size',
      'min-block-size',
      'max-width',
      'max-height',
      'max-inline-size',
      'max-block-size',
      'aspect-ratio',
    ],
    values: ['content-box', 'border-box', '<px>', '<percentage>', 'auto', 'none', '<number>', '<ratio>'],
    parity: ['aspect-ratio', 'box-sizing-min-max-size-constraints', 'min-max-size-constraints', 'percentage-sizing'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Box sizing including CSS-wide content-box resets, pixel and percentage min/max constraints, percentages, and aspect ratio in both axes with constraint interaction have parity fixtures.',
      },
      {
        kind: 'limitation',
        text: 'Length support is intentionally narrow: pixels, percentages where listed, reset keywords, and literal zero.',
      },
    ],
  },
  {
    id: 'box-model-spacing',
    title: 'Margin, padding, border geometry, and gaps',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'margin',
      'margin-inline',
      'margin-block',
      'margin-inline-start',
      'margin-inline-end',
      'margin-block-start',
      'margin-block-end',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-inline',
      'padding-block',
      'padding-inline-start',
      'padding-inline-end',
      'padding-block-start',
      'padding-block-end',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'gap',
      'row-gap',
      'column-gap',
      'border',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-width',
      'border-inline-width',
      'border-block-width',
      'border-inline-start-width',
      'border-inline-end-width',
      'border-block-start-width',
      'border-block-end-width',
      'border-top-width',
      'border-right-width',
      'border-bottom-width',
      'border-left-width',
      'border-style',
      'border-inline-style',
      'border-block-style',
      'border-inline-start-style',
      'border-inline-end-style',
      'border-block-start-style',
      'border-block-end-style',
      'border-top-style',
      'border-right-style',
      'border-bottom-style',
      'border-left-style',
    ],
    values: ['<px>', '<percentage>', 'auto', 'thin', 'medium', 'thick', 'none', 'hidden', 'dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset', 'normal'],
    parity: [
      'border-box-padding-border',
      'border-shorthand',
      'border-width-keywords',
      'border-width-none-style',
      'content-box-padding-border',
      'flex-gap',
      'logical-properties',
      'static-margin-flow',
      'static-parent-padding-border',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Physical and logical box spacing, border geometry, flex and grid gaps on both axes, wrapped flex row gaps, and percentage gaps against definite container sizes have parity fixtures.',
      },
      {
        kind: 'limitation',
        text: 'Margin collapse is not implemented.',
      },
      {
        kind: 'implementation-quirk',
        text: 'Border widths affect geometry for supported border line styles except none and hidden; border painting is not modeled.',
      },
      {
        kind: 'limitation',
        text: 'Percentage spacing values are supported for gap and margin properties; padding and border widths remain limited to pixels and listed keywords.',
      },
      {
        kind: 'implementation-quirk',
        text: 'Logical spacing and border edges are mapped as horizontal-tb LTR; direction and writing-mode are not modeled.',
      },
    ],
  },
  {
    id: 'flex-layout',
    title: 'Flex layout',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'flex',
      'flex-direction',
      'flex-wrap',
      'flex-flow',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'order',
      'align-content',
      'align-items',
      'align-self',
      'justify-content',
      'justify-items',
      'justify-self',
      'place-content',
      'place-items',
      'place-self',
    ],
    parity: [
      'flex-align-content',
      'flex-align-items-stretch',
      'flex-align-self',
      'flex-alignment',
      'flex-auto-margins',
      'flex-basis',
      'flex-direction-reverse',
      'flex-flow',
      'flex-grow',
      'flex-justify-content',
      'flex-order',
      'flex-replaced-intrinsic',
      'flex-row',
      'flex-shorthand',
      'flex-shrink',
      'flex-wrap',
      'place-alignment',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Core row/column, reverse direction, wrapping, alignment including CSS-wide resets, grow and shrink including min/max clamping, auto margins, order including CSS-wide resets, basis, shorthand, and replaced intrinsic cases have parity fixtures.',
      },
      {
        kind: 'implementation-quirk',
        text: 'The CSS order property is applied by sorting flex children before building the Taffy tree.',
      },
    ],
  },
  {
    id: 'grid-layout',
    title: 'Grid layout',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'grid-template-columns',
      'grid-template-rows',
      'grid-auto-flow',
      'grid-auto-columns',
      'grid-auto-rows',
      'grid-column',
      'grid-row',
      'grid-column-start',
      'grid-column-end',
      'grid-row-start',
      'grid-row-end',
      'grid-area',
    ],
    values: [
      'none',
      '<px>',
      '<percentage>',
      '<fr>',
      'minmax(<track-breadth>, <track-breadth>)',
      'repeat(<integer>, <track-list>)',
      'auto',
      '<integer>',
      'span <integer>',
      'row',
      'column',
      'dense',
    ],
    parity: [
      'grid-auto-flow',
      'grid-auto-tracks',
      'grid-content-alignment',
      'grid-explicit-tracks',
      'grid-fr-tracks',
      'grid-gap',
      'grid-area-placement',
      'grid-line-placement',
      'grid-item-stretch',
      'grid-minmax-tracks',
      'grid-order',
      'grid-percentage-tracks',
      'grid-repeat-tracks',
      'grid-span-placement',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Explicit tracks, auto flow including CSS-wide resets, implicit row and column tracks, fr tracks, gaps, content and item alignment, line placement including CSS-wide resets, grid-area shorthand placement including CSS-wide resets, minmax tracks, order, percentage tracks, fixed-count repeat tracks, and numeric spans have parity fixtures.',
      },
      {
        kind: 'limitation',
        text: 'auto-fill/auto-fit repeat counts, named lines, named spans, fit-content(), named grid areas, and grid-template-areas are not implemented.',
      },
      {
        kind: 'limitation',
        text: 'repeat() currently supports positive integer counts with the already-supported track breadth values inside the repeated track list.',
      },
      {
        kind: 'taffy-compat',
        text: 'Flexible fr tracks are mapped to Taffy min/max tracks with min 0 and max Nfr because Taffy only accepts fr as a max track sizing function.',
      },
      {
        kind: 'implementation-quirk',
        text: 'The CSS order property is applied by sorting grid children before building the Taffy tree, so auto-placement sees order-modified children.',
      },
    ],
  },
  {
    id: 'text-measurement',
    title: 'Text measurement',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'text',
    parityStatus: 'partial',
    properties: ['font-family', 'font-size', 'line-height', 'white-space'],
    values: ['<family-list>', '<px>', '<percentage>', '<em>', '<rem>', '<number>', 'normal', 'pre', 'pre-line', 'pre-wrap', 'nowrap'],
    parity: ['static-pre-wrap-text-lines', 'static-text-line-height'],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'Text-only leaf elements and direct text-plus-br leaves are measured through the configured TextMeasurer; the default uses Pretext with deterministic fallback.',
      },
      {
        kind: 'browser-parity',
        text: 'Nested text elements inherit parent font metrics; explicit inherit/unset is accepted for inherited text declarations; initial resets are accepted for font-family, font-size, and white-space; percentage/em font-size values resolve against the inherited parent font size; rem font-size values resolve against the computed root font size; percentage/em line-height values resolve against the element font size; rem line-height values resolve against the computed root font size.',
      },
      {
        kind: 'limitation',
        text: 'The engine does not implement full inline formatting or preserve the distinction between inherited numeric and resolved line-height values.',
      },
    ],
  },
  {
    id: 'generic-html-elements',
    title: 'Generic HTML element layout',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [],
    elements: [
      'html',
      'body',
      'div',
      'section',
      'article',
      'main',
      'header',
      'footer',
      'nav',
      'aside',
      'address',
      'p',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'blockquote',
      'figure',
      'figcaption',
      'pre',
      'hr',
      'br',
      'details',
      'summary',
      'dialog',
    ],
    parity: [
      'details-summary-defaults',
      'dialog-html-defaults',
      'generic-html-defaults',
      'hidden-attribute',
      'figure-html-defaults',
      'hr-html-defaults',
      'static-block-flow',
      'static-pre-wrap-text-lines',
    ],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'The layout tree treats ordinary elements with the same default block style unless author CSS overrides them; address, p, headings, blockquote, figure, and pre receive a narrow set of UA text metrics and spacing defaults.',
      },
      {
        kind: 'limitation',
        text: 'Native dialog centering, modal top-layer behavior, and backdrops are not modeled.',
      },
      {
        kind: 'browser-parity',
        text: 'Address, paragraph, blockquote, figure, pre, hr, details/summary, hidden including until-found, and basic dialog open/closed native behavior have parity coverage in non-collapsing block flow; author CSS reset behavior is also covered.',
      },
      {
        kind: 'limitation',
        text: 'Closed details content is suppressed from layout and hit testing; Chromium still exposes non-zero rects for the suppressed descendants, which this engine does not model.',
      },
    ],
  },
  {
    id: 'non-rendered-html-elements',
    title: 'Non-rendered HTML elements',
    status: 'full',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'covered',
    properties: [],
    elements: ['base', 'link', 'meta', 'noscript', 'script', 'style', 'template', 'title', 'wbr'],
    parity: ['non-rendered-elements'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Metadata, raw-text, template, noscript, and wbr elements with no CSS box are skipped when building the layout and hit-test tree.',
      },
    ],
  },
  {
    id: 'inline-html-elements',
    title: 'Inline phrasing HTML elements',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [],
    elements: [
      'span',
      'a',
      'strong',
      'em',
      'b',
      'i',
      'u',
      's',
      'small',
      'code',
      'kbd',
      'samp',
      'mark',
      'br',
      'sub',
      'sup',
      'time',
      'label',
    ],
    parity: ['inline-html-defaults'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Native inline phrasing elements contribute text through ancestor text measurement without introducing block-flow breaks, including hard line breaks from br elements in inline-only text subtrees.',
      },
      {
        kind: 'limitation',
        text: 'Inline fragment rectangles, inline hit boxes, mixed inline/block formatting, and baseline effects for sub/sup are not modeled; native inline elements currently expose zero rects unless author CSS changes their display.',
      },
    ],
  },
  {
    id: 'list-html-elements',
    title: 'List HTML elements',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [],
    parity: ['list-html-defaults'],
    elements: ['ul', 'ol', 'li', 'dl', 'dt', 'dd', 'menu'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Native ul/ol/menu block margins, inline-start padding, and dd indentation have parity coverage.',
      },
      {
        kind: 'limitation',
        text: 'Marker boxes, marker painting, list-style-position, and browser margin collapse are not modeled.',
      },
    ],
  },
  {
    id: 'table-html-elements',
    title: 'Table HTML elements',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'display: table/table-row/table-cell/table-caption/table-row-group/table-header-group/table-footer-group/table-column/table-column-group',
      'border-collapse',
      'border-spacing',
      'caption-side',
      'empty-cells',
      'table-layout',
      'vertical-align',
    ],
    elements: ['table', 'caption', 'colgroup', 'col', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td'],
    parity: ['css-table-display', 'table-explicit-cells'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Simple native table/caption/colgroup/col/tbody/thead/tfoot/tr/td layout and authored display:table/table-row/table-cell/table-caption/table-row-group boxes with explicit cell and column sizes, numeric table/cell/column width and height attributes, author table width/height scaling, cellspacing/cellpadding defaults with CSS override, direct row children, row and column spans, row/column visibility:collapse, empty-cells hit testing, top/bottom captions including inherited caption-side, wider explicit captions, multiple row groups, visual header/footer ordering, cell padding and borders, uniform collapsed borders, cell hit testing, default/reset/two-axis border spacing, and inert table-layout/vertical-align parsing has parity coverage.',
      },
      {
        kind: 'limitation',
        text: 'The implemented table subset is intentionally narrow and only handles non-spanning rows with explicit cell sizes.',
      },
      {
        kind: 'limitation',
        text: 'Intrinsic column sizing, full collapsed-border conflict resolution, and complex table-specific visibility:collapse interactions are not modeled.',
      },
    ],
  },
  {
    id: 'form-html-elements',
    title: 'Form and interactive HTML elements',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [],
    parity: ['form-control-intrinsic-defaults'],
    elements: [
      'button',
      'input',
      'textarea',
      'select',
      'option',
      'optgroup',
      'fieldset',
      'legend',
      'form',
      'output',
      'progress',
      'meter',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'button, input text-like controls including size attributes, input button/reset/submit, checkbox, radio, range, color, hidden, file, image with explicit attributes, time, textarea including rows/cols attributes, select including size/multiple attributes, progress, and meter intrinsic sizes have parity coverage when author CSS blockifies them.',
      },
      {
        kind: 'implementation-quirk',
        text: 'Common form controls are measured as replaced leaves so option children and anonymous control internals do not participate in the layout tree.',
      },
      {
        kind: 'limitation',
        text: 'Inline form-control formatting, fieldset and legend layout, option popup layout, placeholder text, and most control-specific UA styling are not modeled.',
      },
    ],
  },
  {
    id: 'hit-testing',
    title: 'Hit testing visibility and overflow',
    status: 'partial',
    effect: 'hit-testing',
    ownerArea: 'hit-testing',
    parityStatus: 'covered',
    properties: ['pointer-events', 'visibility', 'overflow', 'overflow-x', 'overflow-y'],
    values: ['auto', 'none', 'visible', 'hidden', 'collapse', 'clip', 'scroll'],
    parity: [
      'center-click-blocked-by-overlay',
      'element-scroll-offsets',
      'elements-from-point-order',
      'overflow-clipping',
      'pointer-events-none',
      'visibility-hidden',
      'window-scroll-offsets',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Point query ordering, pointer-events none including descendant inheritance, inherit/unset preservation, and auto/initial overrides, visibility hidden including descendant inheritance, inherit/unset preservation, and visible/initial overrides, center blocking, overflow clipping, element scroll offsets, and window scroll offsets have parity fixtures.',
      },
      {
        kind: 'behavior-quirk',
        text: 'Overflow hidden, clip, auto, and scroll clip descendant hit boxes to the padding box; getBoundingClientRect output is not clipped.',
      },
      {
        kind: 'implementation-quirk',
        text: 'visibility: collapse is treated as hidden for DOM-like box hit testing; table row and column collapse layout is not modeled.',
      },
    ],
  },
  {
    id: 'visual-only',
    title: 'Visual-only accepted declarations',
    status: 'partial',
    effect: 'visual',
    ownerArea: 'css-parser',
    parityStatus: 'partial',
    properties: [
      'opacity',
      'color',
      'background-color',
      'background',
      'background-image',
      'background-repeat',
      'background-position',
      'background-size',
      'background-origin',
      'background-clip',
      'background-attachment',
      'box-shadow',
      'border-color',
      'border-inline-color',
      'border-block-color',
      'border-top-color',
      'border-right-color',
      'border-bottom-color',
      'border-left-color',
      'border-inline-start-color',
      'border-inline-end-color',
      'border-block-start-color',
      'border-block-end-color',
      'outline',
      'outline-width',
      'outline-style',
      'outline-color',
      'outline-offset',
      'border-radius',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-bottom-right-radius',
      'border-bottom-left-radius',
      'text-decoration',
      'text-decoration-line',
      'text-decoration-color',
      'text-decoration-style',
      'text-decoration-thickness',
      'filter',
      'backdrop-filter',
      'transform',
      'transform-origin',
      'object-fit',
      'object-position',
    ],
    parity: ['visual-only-properties'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Accepted visual-only declarations have parity coverage that they do not affect rectangles or point queries under this package contract.',
      },
      {
        kind: 'limitation',
        text: 'Painting, transforms, decoration rendering, and visual overflow are not modeled.',
      },
    ],
  },
  {
    id: 'inert-ui-and-interaction-hints',
    title: 'Inert UI, interaction, and environment hints',
    status: 'partial',
    effect: 'inert',
    ownerArea: 'css-parser',
    parityStatus: 'partial',
    properties: [
      'will-change',
      'appearance',
      'accent-color',
      'caret-color',
      'scroll-behavior',
      'scrollbar-width',
      'scrollbar-color',
      'overscroll-behavior',
      'overscroll-behavior-x',
      'overscroll-behavior-y',
      'isolation',
      'mix-blend-mode',
      'list-style',
      'list-style-type',
      'list-style-position',
      'list-style-image',
      'forced-color-adjust',
      'color-scheme',
      'cursor',
      'user-select',
      'touch-action',
      'resize',
      'direction',
      'writing-mode',
      'float',
      'clear',
      'contain',
      'container-type',
      'container-name',
    ],
    parity: ['visual-only-properties'],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'These declarations are parsed so common application CSS can pass unsupported-CSS policy, but they do not affect layout or hit testing.',
      },
      {
        kind: 'limitation',
        text: 'Only direction:ltr and writing-mode:horizontal-tb are accepted; non-default writing directions remain unsupported because logical layout is mapped as horizontal-tb LTR.',
      },
      {
        kind: 'limitation',
        text: 'Only float:none and clear:none are accepted; floated layout and float clearance are not modeled.',
      },
      {
        kind: 'limitation',
        text: 'Only contain:none, container-type:normal, and container-name:none are accepted; containment and container query behavior are not modeled.',
      },
    ],
  },
  {
    id: 'custom-properties-and-transitions',
    title: 'Custom properties and transitions',
    status: 'partial',
    effect: 'inert',
    ownerArea: 'css-parser',
    parityStatus: 'not-applicable',
    properties: [
      '--*',
      'transition',
      'transition-property',
      'transition-duration',
      'transition-timing-function',
      'transition-delay',
      'transition-behavior',
    ],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'Custom properties and transition declarations are accepted as inert declarations before value parsing.',
      },
      {
        kind: 'limitation',
        text: 'CSS variable resolution is not implemented, so var() references in supported layout declarations remain unsupported.',
      },
    ],
  },
  {
    id: 'replaced-elements',
    title: 'Replaced element intrinsic sizing',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'covered',
    properties: [],
    elements: ['img', 'svg', 'canvas', 'video', 'audio', 'iframe', 'object'],
    parity: ['replaced-image-attributes'],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'img can use width/height attributes, with missing dimensions treated as zero for no-resource images; svg, canvas, video, iframe, and empty object elements use native 300x150 fallback dimensions with width/height attribute overrides; object elements without type/data resource hints lay out fallback children; audio elements without controls are non-rendered and audio controls use native 300x54 fallback dimensions; any element can use data-layout-width and data-layout-height metadata.',
      },
    ],
  },
  {
    id: 'todo-unimplemented-layout-css',
    title: 'Tracked unimplemented layout CSS',
    status: 'todo',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'missing',
    properties: [
      'direction',
      'writing-mode',
      'float: left/right/inline-start/inline-end',
      'clear: left/right/both/inline-start/inline-end',
      'display: inline formatting',
      'display: list-item markers',
      'grid-template-areas',
      'position: sticky',
      'border-collapse',
      'border-spacing',
      'empty-cells',
      'transform: non-none',
      'contain: layout/paint/size/style/content/strict',
      'container-type: size/inline-size/scroll-state',
      'container-name: <custom-ident>',
    ],
    notes: [
      {
        kind: 'todo',
        text: 'These are tracked because they are likely to matter for layout coherence, but they are not currently accepted as implemented declarations.',
      },
    ],
  },
] as const

export function getInventoriedCssProperties(): string[] {
  return [...new Set(cssSupportInventory.flatMap((entry) => entry.properties))].sort()
}

export function getInventoriedHtmlElements(): string[] {
  return [...new Set(cssSupportInventory.flatMap((entry) => entry.elements ?? []))].sort()
}
