export type CssSupportStatus = 'full' | 'partial' | 'todo'

export type CssSupportEffect = 'layout' | 'hit-testing' | 'visual' | 'inert' | 'source'

export type CssSupportOwnerArea = 'css-parser' | 'taffy-adapter' | 'hit-testing' | 'text' | 'dom-api'

export type CssSupportParityStatus = 'covered' | 'partial' | 'missing' | 'not-applicable'

export type CssSupportNoteKind =
  | 'browser-parity'
  | 'behavior-quirk'
  | 'implementation-quirk'
  | 'taffy-compat'
  | 'limitation'
  | 'todo'

export type CssSupportNote = {
  kind: CssSupportNoteKind
  text: string
}

export type CssSupportEntry = {
  id: string
  title: string
  status: CssSupportStatus
  effect: CssSupportEffect
  ownerArea: CssSupportOwnerArea
  parityStatus: CssSupportParityStatus
  properties: readonly string[]
  values?: readonly string[]
  parity?: readonly string[]
  notes: readonly CssSupportNote[]
}

export const cssSupportInventory: readonly CssSupportEntry[] = [
  {
    id: 'stylesheet-sources-and-selectors',
    title: 'Stylesheet sources and selectors',
    status: 'partial',
    effect: 'source',
    ownerArea: 'css-parser',
    parityStatus: 'partial',
    properties: [],
    parity: ['selector-source-order-tie', 'selector-specificity'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Configured stylesheets, style elements, selector lists, specificity, and source-order ties are covered by parity fixtures.',
      },
      {
        kind: 'limitation',
        text: 'External stylesheets, at-rules, sibling combinators, pseudo-elements, and most pseudo-classes are not implemented.',
      },
    ],
  },
  {
    id: 'display',
    title: 'Display model',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: ['display'],
    values: ['block', 'inline', 'inline-block', 'flow-root', 'list-item', 'flex', 'inline-flex', 'grid', 'inline-grid', 'none'],
    parity: ['display-aliases', 'display-none', 'static-block-flow', 'flex-row', 'grid-explicit-tracks'],
    notes: [
      {
        kind: 'taffy-compat',
        text: 'Inline, inline-block, flow-root, and list-item are blockified; inline-flex and inline-grid are mapped to flex and grid.',
      },
      {
        kind: 'limitation',
        text: 'Inline formatting and list marker layout are not modeled.',
      },
    ],
  },
  {
    id: 'positioning',
    title: 'Positioning and insets',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'covered',
    properties: [
      'position',
      'left',
      'right',
      'top',
      'bottom',
      'inset',
      'inset-inline',
      'inset-block',
      'inset-inline-start',
      'inset-inline-end',
      'inset-block-start',
      'inset-block-end',
      'z-index',
    ],
    values: ['static', 'relative', 'absolute', 'fixed', '<px>', 'auto', '<integer>'],
    parity: [
      'absolute-overlap',
      'absolute-positioned-containing-block',
      'fixed-inset-full-viewport',
      'inset-two-value-shorthand',
      'relative-offset-flow',
      'right-bottom-positioning',
      'z-index-dom-order',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Relative offsets, absolute containing blocks, fixed viewport positioning, opposing insets, and z-index ordering have parity fixtures.',
      },
      {
        kind: 'taffy-compat',
        text: 'Fixed positioning is represented through Taffy absolute positioning in the viewport-rooted layout tree.',
      },
    ],
  },
  {
    id: 'box-sizing-and-dimensions',
    title: 'Box sizing and dimensions',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'box-sizing',
      'width',
      'height',
      'inline-size',
      'block-size',
      'min-width',
      'min-height',
      'min-inline-size',
      'min-block-size',
      'max-width',
      'max-height',
      'max-inline-size',
      'max-block-size',
      'aspect-ratio',
    ],
    values: ['content-box', 'border-box', '<px>', '<percentage>', 'auto', 'none', '<number>', '<ratio>'],
    parity: ['aspect-ratio', 'box-sizing-min-max-size-constraints', 'min-max-size-constraints', 'percentage-sizing'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Box sizing, min/max constraints, percentages, and aspect ratio have parity fixtures.',
      },
      {
        kind: 'limitation',
        text: 'Length support is intentionally narrow: pixels, percentages where listed, reset keywords, and literal zero.',
      },
    ],
  },
  {
    id: 'box-model-spacing',
    title: 'Margin, padding, border geometry, and gaps',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'margin',
      'margin-inline',
      'margin-block',
      'margin-inline-start',
      'margin-inline-end',
      'margin-block-start',
      'margin-block-end',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-inline',
      'padding-block',
      'padding-inline-start',
      'padding-inline-end',
      'padding-block-start',
      'padding-block-end',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'gap',
      'row-gap',
      'column-gap',
      'border',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-width',
      'border-inline-width',
      'border-block-width',
      'border-inline-start-width',
      'border-inline-end-width',
      'border-block-start-width',
      'border-block-end-width',
      'border-top-width',
      'border-right-width',
      'border-bottom-width',
      'border-left-width',
      'border-style',
      'border-inline-style',
      'border-block-style',
      'border-inline-start-style',
      'border-inline-end-style',
      'border-block-start-style',
      'border-block-end-style',
      'border-top-style',
      'border-right-style',
      'border-bottom-style',
      'border-left-style',
    ],
    values: ['<px>', 'thin', 'medium', 'thick', 'none', 'solid', 'normal'],
    parity: [
      'border-box-padding-border',
      'border-shorthand',
      'border-width-none-style',
      'content-box-padding-border',
      'flex-gap',
      'logical-properties',
      'static-margin-flow',
      'static-parent-padding-border',
    ],
    notes: [
      {
        kind: 'limitation',
        text: 'Margin collapse is not implemented.',
      },
      {
        kind: 'implementation-quirk',
        text: 'Border widths affect geometry only for edges whose supported border style is solid.',
      },
      {
        kind: 'implementation-quirk',
        text: 'Logical spacing and border edges are mapped as horizontal-tb LTR; direction and writing-mode are not modeled.',
      },
    ],
  },
  {
    id: 'flex-layout',
    title: 'Flex layout',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'flex',
      'flex-direction',
      'flex-wrap',
      'flex-flow',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'align-content',
      'align-items',
      'align-self',
      'justify-content',
      'justify-items',
      'justify-self',
      'place-content',
      'place-items',
      'place-self',
    ],
    parity: [
      'flex-align-content',
      'flex-align-self',
      'flex-alignment',
      'flex-basis',
      'flex-direction-reverse',
      'flex-flow',
      'flex-grow',
      'flex-replaced-intrinsic',
      'flex-row',
      'flex-shorthand',
      'flex-wrap',
      'place-alignment',
    ],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Core row/column, reverse direction, wrapping, alignment, grow, basis, shorthand, and replaced intrinsic cases have parity fixtures.',
      },
      {
        kind: 'taffy-compat',
        text: 'Flex behavior is delegated to Taffy where the supported CSS value has a Taffy equivalent.',
      },
    ],
  },
  {
    id: 'grid-layout',
    title: 'Grid layout',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'partial',
    properties: [
      'grid-template-columns',
      'grid-template-rows',
      'grid-auto-columns',
      'grid-auto-rows',
      'grid-column',
      'grid-row',
      'grid-column-start',
      'grid-column-end',
      'grid-row-start',
      'grid-row-end',
    ],
    values: ['none', '<px>', '<percentage>', 'auto', '<integer>'],
    parity: ['grid-auto-tracks', 'grid-explicit-tracks', 'grid-line-placement', 'grid-percentage-tracks'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Explicit tracks, auto tracks, line placement, and percentage tracks have parity fixtures.',
      },
      {
        kind: 'limitation',
        text: 'fr units, repeat(), named lines, spans, and grid areas are not implemented.',
      },
    ],
  },
  {
    id: 'text-measurement',
    title: 'Text measurement',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'text',
    parityStatus: 'partial',
    properties: ['font-family', 'font-size', 'line-height', 'white-space'],
    values: ['<family-list>', '<px>', '<number>', 'normal', 'pre-wrap', 'nowrap'],
    parity: ['static-pre-wrap-text-lines', 'static-text-line-height'],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'Text-only leaf elements are measured through the configured TextMeasurer; the default uses Pretext with deterministic fallback.',
      },
      {
        kind: 'limitation',
        text: 'The engine does not implement full inline formatting.',
      },
    ],
  },
  {
    id: 'hit-testing',
    title: 'Hit testing visibility and overflow',
    status: 'partial',
    effect: 'hit-testing',
    ownerArea: 'hit-testing',
    parityStatus: 'covered',
    properties: ['pointer-events', 'visibility', 'overflow', 'overflow-x', 'overflow-y'],
    values: ['auto', 'none', 'visible', 'hidden', 'clip'],
    parity: ['center-click-blocked-by-overlay', 'elements-from-point-order', 'overflow-clipping', 'pointer-events-none', 'visibility-hidden'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Point query ordering, pointer-events none, visibility hidden, center blocking, and overflow clipping have parity fixtures.',
      },
      {
        kind: 'behavior-quirk',
        text: 'Overflow hidden and clip clip descendant hit boxes to the padding box; getBoundingClientRect output is not clipped.',
      },
    ],
  },
  {
    id: 'visual-only',
    title: 'Visual-only accepted declarations',
    status: 'partial',
    effect: 'visual',
    ownerArea: 'css-parser',
    parityStatus: 'partial',
    properties: [
      'opacity',
      'color',
      'background-color',
      'background',
      'background-image',
      'background-repeat',
      'background-position',
      'background-size',
      'background-origin',
      'background-clip',
      'background-attachment',
      'box-shadow',
      'border-color',
      'border-inline-color',
      'border-block-color',
      'border-top-color',
      'border-right-color',
      'border-bottom-color',
      'border-left-color',
      'border-inline-start-color',
      'border-inline-end-color',
      'border-block-start-color',
      'border-block-end-color',
      'outline',
      'outline-width',
      'outline-style',
      'outline-color',
      'outline-offset',
      'border-radius',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-bottom-right-radius',
      'border-bottom-left-radius',
      'text-decoration',
      'text-decoration-line',
      'text-decoration-color',
      'text-decoration-style',
      'text-decoration-thickness',
      'filter',
      'backdrop-filter',
      'transform-origin',
      'object-fit',
      'object-position',
    ],
    parity: ['visual-only-properties'],
    notes: [
      {
        kind: 'browser-parity',
        text: 'Accepted visual-only declarations have parity coverage that they do not affect rectangles or point queries under this package contract.',
      },
      {
        kind: 'limitation',
        text: 'Painting, transforms, decoration rendering, and visual overflow are not modeled.',
      },
    ],
  },
  {
    id: 'inert-ui-and-interaction-hints',
    title: 'Inert UI, interaction, and environment hints',
    status: 'partial',
    effect: 'inert',
    ownerArea: 'css-parser',
    parityStatus: 'partial',
    properties: [
      'will-change',
      'appearance',
      'accent-color',
      'caret-color',
      'scroll-behavior',
      'scrollbar-width',
      'scrollbar-color',
      'overscroll-behavior',
      'overscroll-behavior-x',
      'overscroll-behavior-y',
      'isolation',
      'mix-blend-mode',
      'list-style',
      'list-style-type',
      'list-style-position',
      'list-style-image',
      'forced-color-adjust',
      'color-scheme',
      'cursor',
      'user-select',
      'touch-action',
      'resize',
    ],
    parity: ['visual-only-properties'],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'These declarations are parsed so common application CSS can pass unsupported-CSS policy, but they do not affect layout or hit testing.',
      },
    ],
  },
  {
    id: 'custom-properties-and-transitions',
    title: 'Custom properties and transitions',
    status: 'partial',
    effect: 'inert',
    ownerArea: 'css-parser',
    parityStatus: 'not-applicable',
    properties: [
      '--*',
      'transition',
      'transition-property',
      'transition-duration',
      'transition-timing-function',
      'transition-delay',
      'transition-behavior',
    ],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'Custom properties and transition declarations are accepted as inert declarations before value parsing.',
      },
      {
        kind: 'limitation',
        text: 'CSS variable resolution is not implemented, so var() references in supported layout declarations remain unsupported.',
      },
    ],
  },
  {
    id: 'replaced-elements',
    title: 'Replaced element intrinsic sizing',
    status: 'partial',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'covered',
    properties: [],
    parity: ['replaced-image-attributes'],
    notes: [
      {
        kind: 'implementation-quirk',
        text: 'img, svg, canvas, and video can use width/height attributes; any element can use data-layout-width and data-layout-height metadata.',
      },
    ],
  },
  {
    id: 'todo-unimplemented-layout-css',
    title: 'Tracked unimplemented layout CSS',
    status: 'todo',
    effect: 'layout',
    ownerArea: 'taffy-adapter',
    parityStatus: 'missing',
    properties: [
      'direction',
      'writing-mode',
      'float',
      'clear',
      'display: inline formatting',
      'display: list-item markers',
      'grid-template-areas',
      'grid-area',
      'grid-auto-flow',
      'order',
      'position: sticky',
      'transform',
      'contain',
      'container-type',
      'container-name',
    ],
    notes: [
      {
        kind: 'todo',
        text: 'These are tracked because they are likely to matter for layout coherence, but they are not currently accepted as implemented declarations.',
      },
    ],
  },
] as const

export function getInventoriedCssProperties(): string[] {
  return [...new Set(cssSupportInventory.flatMap((entry) => entry.properties))].sort()
}
